language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t kushagradocker/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true kushagradocker/docker-react npm run test